mirage/ocaml-9p

.travis.yml
README.md
lib/client.ml
lib/request.ml
lib/request.mli
lib/response.ml
lib/response.mli
lib/types.ml
lib/types.mli
lib_test/tests.ml
src/main.ml

The library now requests the 9P2000.u protocol by default.

Support 9P2000.u

---

_oasis
lib/buffered9PReader.ml
lib/buffered9PReader.mli
lib/client.ml
lib/server.ml
lib/server.mli
lib/types.ml
lib/types.mli
src/main.ml

The command:
```
./main.native serve -a 127.0.0.1:8081 /
```
is now capable of responding to
```
./main.native ls / --address 127.0.0.1:8081
```

Add basic server implementation

---

.merlin
_oasis
lib/buffered9PReader.ml
lib/filesystem.mli
lib/handler.ml
lib/handler.mli
lib/infix.ml
lib/infix.mli
lib/server.ml
lib/server.mli
src/main.ml
unix/lofs9p.ml
unix/lofs9p.mli

Factor out loopback file system and add Stat

---

.coveralls.sh
.gitignore
.travis.yml
Makefile
_oasis
lib_test/tests.ml

Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

coverage: Switch to ocaml-travis-coveralls

---

README.md
_oasis
opam

Also add David Sheets and Thomas Leonard as Authors in _oasis and opam.

Update references to mirage/ from djs55/

---

lib/client.ml
lib/request.ml
lib/request.mli
lib/types.ml
lib/types.mli
lib_test/tests.ml
src/main.ml
unix/lofs9p.ml

Lofs9p: More wstat improvements and open mode fixes

---

lib/server.ml

Currently, the server waits for the handler to generate a response before processing the next query.
This means that if the client reads from a blocking stream then the whole filesystem locks up.
This patch is my (possibly rather hopeful) attempt to fix this by adding a `Lwt.async` around the handler call. Any reason why that shouldn't work?
Seems to work in my test case (true, my dev VM did kernel-panic shortly afterwards in the 9p code, but I think that was a coincidence... or at least due to me ctrl-c'ing the server at a bad time).

[RFC] Process requests asynchronously

---

lib_test/lofs_test.ml

lofs_test: more alcotest updates

---

lib/types.ml
lib/types.mli
unix/lofs9p.ml

- support hard links (even though the world is divided over whether this is in 9p2000.u or not)
- support `OAPPEND` open mode (even though this would appear to be a no-op)
After this PR it is possible to `git commit` and `git clone` on Linux on top of `lofs`.

Make the Linux client happier

---

CHANGES.md

Prepare to release v0.1

---

CHANGES.md

Prepare to release 0.4.0

---

lib/protocol_9p_buffered9PReader.ml

With an msize of 32768, I see a ~15% speedup.

Remove a reader copy in Protocol_9p_buffered9PReader

---

.travis.yml
lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
lib_test/lofs_test.ml
opam
src/_tags
src/main.ml
unix/client9p_unix.ml
unix/client9p_unix.mli
unix/server9p_unix.ml
unix/server9p_unix.mli

The shell allows you to:
- list directories
- change directories
- create files
- create directories
- delete files/directories
- read the contents of files
- write the contents of files
It's very basic but allows simple debugging.

Easier support for Unix domain sockets, and a mini "shell" for debugging

---

Makefile
src/main.ml
unix/client9p_unix.ml
unix/protocol_9p_unix.mllib

Add `module Server9p_unix` to the unix package

---

src/main.ml

The high-level `read` function will return short only if it has hit
`Eof`, so we don't need to call it again to get a `read` of 0 (in fact
we shouldn't if we're doing some fancy stream thing over the file)

shell: fix `read` handling of `Eof`

---

Makefile
lib/protocol_9p.mli
lib/protocol_9p_server.ml
lib/protocol_9p_server.mli

- export `Info`
- add the ability to post-process errors before they are transmitted to the client

More interface improvements

---

lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
lib/protocol_9p_types.ml
lib/protocol_9p_types.mli
unix/client9p_unix.ml

Note: wasn't sure whether to put `update` in `LowLevel` (because it takes a FID) or in `Client` (because it's a wrapper).

Add wstat/update to client API

---

unix/flow_lwt_unix.ml

When the peer closes its socket, Unix `write` will raise EPIPE, rather
than return 0. The FLOW API says this should be represented as an
`Eof value, not an exception (which may bubble up and kill your
program)

Flow_lwt_unix: catch EPIPE, return `Eof

---

CHANGES.md
META
opam

Prepare to release 0.5.0

---

lib/_tags
lib/protocol_9p_request.ml
lib/protocol_9p_request.mli
lib/protocol_9p_response.ml
lib/protocol_9p_response.mli
lib/protocol_9p_types.ml
lib/protocol_9p_types.mli
lib_test/_tags
opam

This PR also adds a missing dependency of `make test`

Remove camlp4, use ppx

---

CHANGES.md
META
opam

Prepare to release 0.6.0

---

lib/protocol_9p_client.ml

The spec says
> The remove request asks the file server both to remove the file
> represented by fid and to clunk the fid, even if the remove fails.
so we must not clunk the fid as well, since it may now be in use by
another operation.
Fixes #79

Client: don't clunk the fid after the remove call

---

src/_tags

Fix for omitted dependencies

---

pkg/META

Signed-off-by: Thomas Leonard <thomas.leonard@docker.com>

The unix module depends on cstruct.lwt

---

unix/client9p_unix.ml

Also, return a better error message in this case and return it as a result rather than as an exception.
Fixes #96.

Close socket if we get an error trying to connect

---

lib/protocol_9p_client.ml

This is a common cause of deadlock (e.g. https://github.com/docker/datakit/pull/228).

Log a message when FID pool is exhausted

---

.travis.yml

Needed for tests to pass if #99 is not reverted.

use mirage-dev extra remote while mirage3 is brewing

---

.travis.yml
appveyor.yml
lib/protocol_9p_client.ml
unix/client9p_unix.ml
unix/flow_lwt_unix.ml

There is now a `mirage-dev` branch to prepare Mirage3

Restore compat with released packages

---

appveyor.yml
lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
lib_test/tests.ml
unix/client9p_unix.ml
unix/client9p_unix.mli

Keep the same default as before (100) but allow to request more.

Allow clients to set the number of fids they will use

---

CHANGES.md
pkg/META

Prepare to release v0.9.0

---

lib/protocol_9p_server.ml

Allows logging them with their request.
This is from #118 about which @talex5 writes:
> When logging exceptions, include the 9p request that triggered it for debugging. Maybe the signature of exn_converter should be changed instead?

Log uncaught exceptions before passing them to exn_converter

---

unix/flow_lwt_unix.ml

Protect Flow_lwt_unix.read and write against End_of_file exceptions

---

.travis.yml
CHANGES.md
appveyor.yml
lib/jbuild
lib_test/jbuild
protocol-9p-tool.opam
protocol-9p-unix.opam
protocol-9p.opam
src/jbuild
unix/jbuild

- add dependency on io-page-unix
- modernise travis and appveyor
- prepare to release v0.11.2

Add dependency on io-page-unix

---

protocol-9p-tool.opam
protocol-9p-unix.opam
protocol-9p.opam

Remove unnecessary dependency on ppx_deriving

---

CHANGES.md

Prepare to release v0.12.0

---

lib/dune
lib/protocol_9p_buffered9PReader.ml
lib/protocol_9p_buffered9PReader.mli
lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
lib/protocol_9p_server.ml
lib/protocol_9p_server.mli
lib/protocol_9p_types.ml
lib_test/dune
protocol-9p-tool.opam
protocol-9p-unix.opam
protocol-9p.opam
unix/dune
unix/flow_lwt_unix.ml
unix/flow_lwt_unix.mli
unix/lofs9p.ml

port to newer mirage interfaces (-lwt/_lwt be gone)

---

CHANGES.md

Prepare to release v2.0.2
