mirage/ocaml-9p

lib/server.ml

Without this, the mortdeus client complains:
can't cd to file [/]

The root should be a directory, not a file

---

opam

Error was:
File "unix/lofs9p.ml", line 75, characters 4-5:
Parse error: [match_case0] expected (in [match_case])

Require OCaml >= 4.02.0

---

lib/buffered9PReader.ml
lib/client.ml
lib/filesystem.mli
lib/handler.ml
lib/request.ml
lib/request.mli
lib/server.ml
lib/types.ml
lib/types.mli
unix/lofs9p.ml

Stat names are fixed, stat struct is fixed, walking is fixed, more infix factoring, error handling is more graceful (but server is more verbose), wstat request parsing bug fixed, added create, added remove, fixed some style issues previously introduced, added wstat 'any' concept, implemented wstat length and wstat name. Review welcome.

Improving lofs9p

---

lib/filesystem.mli
lib/handler.ml
lib/response.ml
lib/response.mli
unix/lofs9p.ml

Before, any method could return any response type. Now, a filesystem function must return the appropriate response type for the request, or an error to be returned to the client.
Errors are converted to the appropriate format based on the protocol version (errno is suppressed if the format does not include it, and a default is added if errno is needed and not present).
Note: wasn't sure what you want to do with errors serialising directory entries. For now, I added an `errors_to_client` function that turns them into protocol errors. They probably shouldn't happen though, so you might prefer an assert.

Improve type safety and error reporting of Handler

---

.merlin
_oasis
lib/client.ml
lib/client.mli
lib/server.ml
lib/server.mli
src/main.ml
unix/client9p_unix.ml
unix/client9p_unix.mli
unix/log9p_unix.ml
unix/log9p_unix.mli

These changes start to factor out useful components from the main example program so they can be reused. Most of the substantive changes relate to resource clean up.
@talex5 review please.

Break out unix-dependent logging and client; add server after_disconnect

---

lib/buffered9PReader.ml
lib/buffered9PReader.mli
lib/request.ml
lib/request.mli
lib/response.ml
lib/response.mli
lib/types.ml
unix/flow_lwt_unix.ml
unix/log9p_unix.ml

Would be nice to compile with warnings on by default, but I don't see how to do that with oasis without committing the `_tags` file (which we seem to be avoiding).

Fix some compiler warnings

---

lib/client.ml
lib/client.mli
unix/client9p_unix.ml

Otherwise, the `Client.LowLevel` API cannot be used, because all the functions require a fid but there is no way to get one (other than making them from ints, but that isn't safe since you don't know which ones the client has allocated for itself).
I expose `walk_from_root` rather than just `root` so callers can't mess up the root fid.

Provide a way to get Fids

---

lib/filesystem.mli
lib/handler.ml
lib/server.ml
lib/server.mli
src/main.ml
unix/lofs9p.ml

When a flush request arrives, we send a cancellation signal to any active worker thread and prevent the original thread returning a response after the flush response has been sent.
This is enough to satisfy the Linux 9P client, as triggered by Control+C.

Support cancel/flush

---

lib/server.ml

When performing lots of I/O, the debug logging will generate a lot of
strings via expensive s-expression printing.
Eventually this will be made conditional via a variant of #18.

Avoid debug logging on every packet sent and received

---

lib_test/lofs_test.ml
src/main.ml
unix/lofs9p.ml
unix/server9p_unix.ml

When `create` succeeds, the fid should be rebound from the parent to the child.

Test and fix create (fid should be rebound)

---

lib/client.ml
lib/client.mli
lib_test/lofs_test.ml
src/main.ml
unix/client9p_unix.ml
unix/lofs9p.ml

- Add client helper for `remove`
- Fix `lofs` implementation of `remove` for directories
- Add test case for file remove
- Add test case for directory remove
- Make the `lofs` test cleanup more robust

lofs: Fix directory remove

---

lib/filesystem.mli
lib/handler.ml
src/main.ml
unix/lofs9p.ml

- respond to multiple `Attach` calls
- include the extension `Stat` fields
- allow symlink creation

Fix linux 9p2000.u mounts

---

lib_test/lofs_test.ml
unix/lofs9p.ml

- walk should fail if the newfid is in use (if it is not the same as fid)
- remove should clunk the fid in the failure case
- associate open fid with file or directory handles
- `read` and `write` of a closed fid now return `bad fid`
- handle out-of-bounds directory reading a bit better

lofs fid improvements

---

lib/server.ml

Before this patch we were in an inconsistent situation where the first
`attach` was handled magically by the server functor, while all subsequent
`attach` requests had to be handled by the user module. This led to the
initial `root_fid` being special-cased.
This patch requires the user module to handle all `attach` requests, making
it easier for the user module to maintain a table of active fids (i.e.
no need for special-casing the `root_fid`)

Server: call `receive_cb` on initial `Attach`

---

lib/response.ml
lib/response.mli
lib/server.ml
lib/server.mli
unix/lofs9p.ml

Some clients will negotiate an `msize` of (e.g.) 16384 and then issue a
`read` with `count=65536`, and then complain when they receive that
many bytes back. This patch makes `lofs` respect the negotiated `msize`
in `read` by returning as many bytes as possible, up to the `msize`.

lofs: respect msize in `read`

---

lib/server.ml
lib/types.ml
opam

This patchset fixes some issues with the mount-time `attach` message handling. It calls the callback's `attach` message so that the file system can perform actions consistently on all `attach` message including the first. There are also a number of other minor improvements.

Mount attach message clean-up

---

lib/protocol_9p_request.ml
lib/protocol_9p_response.ml
lib/protocol_9p_types.ml
lib/protocol_9p_types.mli

Read response and write request only print the size of the payloads.
Also, add some int and int32 projectors for Tags and Fids.

When pretty-printing request and response packets, don't print payloads

---

unix/lofs9p.ml

Uses `iounit` of 0 instead of 512 for much larger packets (`msize - PKT_HEADER` instead of max 512).

Speedup lofs sequential read/write by 9-10x

---

lib/protocol_9p_client.ml
lib/protocol_9p_server.ml
lib_test/lofs_test.ml
opam
unix/server9p_unix.ml

Before this patch we would use `Lwt.async` to launch dispatcher
loops. Unfortunately some I/O errors manifest as exceptions/Lwt
failures (e.g. `Unix.Unix_error(Unix.SIGPIPE,_,_)`) which would
cause the `Lwt.async` to call the default async exception hook
which would quit the program.
This patch catches these errors and logs the fact that the connection
to the remote has failed.

Handle I/O errors in dispatcher loops

---

lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
lib_test/lofs_test.ml
unix/client9p_unix.ml
unix/flow_lwt_unix.ml

Better handling of I/O errors:
- ensure that blocked threads are woken up with errors if the dispatcher thread shuts down (otherwise they'd block forever)
- allow clients to detect whether a connection has been shutdown by exposing using the `on_disconnect` thread
- make `Flow_lwt_unix.close` idempotent for extra safety
Misc improvements:
- expose low-level fid allocation and deallocation functions to support use-cases like keeping files open permanently which didn't fit the `with_fid` pattern
Note the library doesn't handle reconnection itself, but perhaps it will in future.

Allow clients to handle I/O errors, reconnections

---

lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
unix/client9p_unix.ml

This is consistent with the `after_disconnect` exposed by the server.

Client: rename `on_disconnect` to `after_disconnect`

---

lib/protocol_9p_buffered9PReader.ml
lib/protocol_9p_buffered9PReader.mli
lib/protocol_9p_server.ml

This is probably some kind of DoS attack. Also, we would interpret large numbers as negative, leading to:
Invalid_argument "Bigarray.create: negative dimension"
Found using the new OCaml AFL support at https://github.com/ocamllabs/opam-repo-dev/pull/23/files

Reject messages longer than 640 KB

---

opam

Lwt >= 2.4.7 is needed for Lwt.Infix.

Fix opam dependencies

---

opam

This dependency is unnecessary.

opam: remove dependency on ctypes

---

lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
unix/client9p_unix.ml

The API requires the client not to exceed this, but didn't provide a way
to find out what the limit was.
Signed-off-by: Thomas Leonard <thomas.leonard@docker.com>

Add maximum_write_payload to client API

---

lib/protocol_9p_server.ml

Previously the dispatcher loop would handle the Eof by calling
```
let rec dispatcher_t ... =
...
| Error (`Msg message) ->
debug (fun f -> f "S error reading: %s" message);
debug (fun f -> f "Disconnecting client");
disconnect ()
>>= fun () ->
```
where `disconnect` would set the flag and block:
```
let disconnect () =
t.please_shutdown <- true;
t.shutdown_complete_t
```
Unfortunately it is the next cycle of the dispatcher which runs
```
let rec dispatcher_t ... =
if t.please_shutdown then begin
Lwt.wakeup_later shutdown_complete_wakener ();
```
So before this patch the dispatcher would deadlock. This patch makes
the dispatcher set the flag only, execute the next cycle, call wakeup_later
and return. This allows the surrounding application to call `after_shutdown`
and then to close the …

server: fix deadlock when read returns `Eof

---

META
lib/_tags
lib/protocol_9p_buffered9PReader.ml
lib/protocol_9p_buffered9PReader.mli
lib/protocol_9p_request.ml
lib/protocol_9p_request.mli
lib/protocol_9p_response.ml
lib/protocol_9p_server.ml
lib_test/_tags
lib_test/tests.ml
opam
unix/flow_lwt_unix.ml

- use the `Channel` functor to construct a buffered channel over a `FLOW`
- bump the Linux read buffer size (which limits the number of bytes `read` in one syscall) to 32KiB, which also happens to be the default Linux kernel client msize.
In the case where the whole packet payload is read in one go, this will avoid unnecessary data copies. Unfortunately if the payload is split over multiple `Cstruct.t`s then we must call `Cstruct.concat` because all the unmarshalling functions operate over `Cstruct.t` values and not `Cstruct.t list` values.

Use Channel rather than reinvent buffering over FLOW

---

CHANGES.md
src/_tags
src/main.ml

Before this PR the CLI still contained stringext references. This PR removes them.

Remove the rest of stringext

---

lib/protocol_9p_client.ml
unix/client9p_unix.ml

I suspect that translating any errors to `Unknown_key` is wrong and would appreciate any suggestions or followon PRs with better behavior.

Add `mem` function to KV_RO implementation.

---

protocol-9p-unix.opam
protocol-9p.opam
unix/server9p_unix.ml

Lwt_unix.bind now returns a promise.
Related to https://github.com/ocsigen/lwt/issues/308

Update to new lwt.3.0.0 API

---

lib_test/jbuild
src/jbuild
unix/jbuild

`protocol-9p` uses `mirage-channel` which uses `io-page` which will fail to link on Unix without a dependency to `io-page.unix`. 
/cc @djs55

protocol-9p-unix needs io-page.unix to link properly

---

protocol-9p.opam
unix/client9p_unix.ml
unix/client9p_unix.mli
unix/jbuild

This is a tweaked subset of #118, about which @talex5 writes:
> While a connection is open, send a ping message (walk to /) every 30s. This avoids problems in some networks where TCP connections may silently stop working after a while unless there is traffic to keep the connection alive. It also reports these ping times as prometheus metrics. This should probably be optional.
Note this is now optional and can be activated with `connect ~send_pings:true`

client: ping server, add prometheus metrics

---

.travis.yml
CHANGES.md
appveyor.yml
protocol-9p-unix.opam
protocol-9p.opam

- update `CHANGES.md`
- move the `prometheus` dependency to the `protocol-9p-unix.opam` file
- ensure that travis and appveyor installs the `protocol-9p-unix` package, needed by the tests

Prepare to release v0.11.0

---

CHANGES.md
lib/jbuild
protocol-9p-unix.opam
protocol-9p.opam
unix/jbuild

The `cstruct-lwt` package depends on `lwt.unix` and is only needed by `protocol-9p-unix`.

Remove unnecessary Unix dependency

---

CHANGES.md
lib_test/jbuild
protocol-9p-unix.opam
protocol-9p.opam
unix/client9p_unix.ml
unix/jbuild

The `named-pipe` repo was deprecated and archived because its premise that a Windows named pipe could be treated like a Unix file descriptor was false. Named pipe users should use the `Uwt` library, construct a `FLOW` and instantiate the 9P client/server from that.
This PR also removes an unnecessary dependency on `cmdliner` from the core code and prepares to release 0.12.1.

Remove broken named pipe support

---

CHANGES.md
lib/dune
lib/protocol_9p_client.ml
lib/protocol_9p_client.mli
protocol-9p.opam
unix/client9p_unix.ml

This is holding back the mirage universe due to an upper bound on mirage-kv-lwt<2.  However, removing it does not seem to break any dependencies as datakit/vpnkit do not use KV_RO from 9p_client.
@djs55 do you know of any uses? Otherwise I'll just merge this and cut a quick release so docs.mirage.org can use the latest mirage libs.

remove old mirage-kv usage

---

protocol-9p-tool.opam
protocol-9p-unix.opam
protocol-9p.opam

This directive results in failure when downgrading Dune versions, due to version-specific functionality in the Dune language. See https://github.com/ocaml/opam/issues/3850 for more details.

opam: remove the 'build' directive on dune dependency

---

src/main.ml

This PR is a quick fix to make protocal-9p-tool compatible with lambda-term2.

compatible with lambda-term 2

---

CHANGES.md
appveyor.yml
lib/dune
lib/protocol_9p_buffered9PReader.ml
lib/protocol_9p_client.ml
lib/protocol_9p_error.ml
lib/protocol_9p_request.ml
lib/protocol_9p_response.ml
lib/protocol_9p_types.ml
lib_test/lofs_test.ml
lib_test/tests.ml
protocol-9p-tool.opam
protocol-9p-unix.opam
protocol-9p.opam
src/main.ml
unix/flow_lwt_unix.ml
unix/lofs9p.ml

Also
- sync the opam files from opam-repository.
- update lower-bounds on mirage-flow, mirage-channel (was mirage-flow-lwt, mirage-channel-lwt)
- add missing dependency on `logs` in `lib/dune`
- update appveyor to 4.08

Use Cstruct.length (6.0.0+) and Fmt.str rather than Fmt.strf
